// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/admins': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins.post').default>>>>
    }
    '/api/admin/admins/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins/[id].delete').default>>>>
    }
    '/api/admin/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/[id].delete').default>>>>
    }
    '/api/admin/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/index.post').default>>>>
    }
    '/api/admin/chat/:sessionId/reply': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/chat/[sessionId]/reply.post').default>>>>
    }
    '/api/admin/chat': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/chat/index.get').default>>>>
    }
    '/api/admin/flash-sale/config': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/config.post').default>>>>
    }
    '/api/admin/flash-sale/sessions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/[id].patch').default>>>>
    }
    '/api/admin/flash-sale/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/index.get').default>>>>
    }
    '/api/admin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login.post').default>>>>
    }
    '/api/admin/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/logout.post').default>>>>
    }
    '/api/admin/orders/:id/cancel': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/cancel.patch').default>>>>
    }
    '/api/admin/orders/:id/notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/notify.post').default>>>>
    }
    '/api/admin/orders/:id/shipment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/shipment.post').default>>>>
    }
    '/api/admin/orders/:id/status': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/status.patch').default>>>>
    }
    '/api/admin/orders/:id/upload-proof': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/upload-proof.post').default>>>>
    }
    '/api/admin/orders/bulk-notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/bulk-notify.post').default>>>>
    }
    '/api/admin/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/index.get').default>>>>
    }
    '/api/admin/orders/offline': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/offline.post').default>>>>
    }
    '/api/admin/plans/:id': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/plans/[id].patch').default>>>>
    }
    '/api/admin/plans': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/plans/index.get').default>>>>
    }
    '/api/admin/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/[id].delete').default>>>>
    }
    '/api/admin/products/:id/stock': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/[id]/stock.patch').default>>>>
    }
    '/api/admin/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/index.post').default>>>>
    }
    '/api/admin/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.put').default>>>>
    }
    '/api/admin/stores/:id/status': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stores/[id]/status.patch').default>>>>
    }
    '/api/admin/stores': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/stores/index.get').default>>>>
    }
    '/api/admin/subscriptions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/subscriptions/index.get').default>>>>
    }
    '/api/admin/wa-template': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/wa-template.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/wa-template.put').default>>>>
    }
    '/api/analytics-config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/analytics-config.get').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/send-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/send-otp.post').default>>>>
    }
    '/api/auth/verify-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verify-otp.post').default>>>>
    }
    '/api/buyer/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buyer/orders.get').default>>>>
    }
    '/api/buyer/password': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buyer/password.patch').default>>>>
    }
    '/api/buyer/profile': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buyer/profile.patch').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
    }
    '/api/chat/:sessionId/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/[sessionId]/messages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/[sessionId]/messages.post').default>>>>
    }
    '/api/chat/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/start.post').default>>>>
    }
    '/api/checkout/regular': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout/regular.post').default>>>>
    }
    '/api/cron/cleanup-media': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/cleanup-media').default>>>>
    }
    '/api/cron/reconcile-counters': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/reconcile-counters').default>>>>
    }
    '/api/cron/store-expiry': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/cron/store-expiry').default>>>>
    }
    '/api/flash-sale/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/flash-sale/config.get').default>>>>
    }
    '/api/orders/:id/track': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id]/track.get').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.get').default>>>>
    }
    '/api/payment/callback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/callback.post').default>>>>
    }
    '/api/payment/create-transaction': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/create-transaction.post').default>>>>
    }
    '/api/payment/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/settings.get').default>>>>
    }
    '/api/payment/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/status.get').default>>>>
    }
    '/api/plans': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/plans.get').default>>>>
    }
    '/api/products/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
    }
    '/api/products/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/status.get').default>>>>
    }
    '/api/products/stock': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/stock.get').default>>>>
    }
    '/api/s3-image/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/s3-image/[...path].get').default>>>>
    }
    '/api/shipping/cities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shipping/cities.get').default>>>>
    }
    '/api/shipping/cost': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shipping/cost.get').default>>>>
    }
    '/api/sitemap-stores.xml': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/sitemap-stores.xml.get').default>>>>
    }
    '/api/store/:id/image': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/image.post').default>>>>
    }
    '/api/store/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/index.get').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/index.patch').default>>>>
    }
    '/api/store/:id/media/:mid': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/media/[mid].delete').default>>>>
    }
    '/api/store/:id/media/confirm': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/media/confirm.post').default>>>>
    }
    '/api/store/:id/media/presign': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/media/presign.post').default>>>>
    }
    '/api/store/:id/orders/:oid/shipment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/orders/[oid]/shipment.post').default>>>>
    }
    '/api/store/:id/orders/:oid/status': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/orders/[oid]/status.patch').default>>>>
    }
    '/api/store/:id/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/orders/index.get').default>>>>
    }
    '/api/store/:id/products/:pid': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/products/[pid].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/products/[pid].patch').default>>>>
    }
    '/api/store/:id/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/products/index.post').default>>>>
    }
    '/api/store/:id/quota': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/quota.get').default>>>>
    }
    '/api/store/:id/subscribe': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/subscribe.post').default>>>>
    }
    '/api/store/:id/vouchers/:voucherId': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/vouchers/[voucherId].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/vouchers/[voucherId].patch').default>>>>
    }
    '/api/store/:id/vouchers': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/vouchers/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/[id]/vouchers/index.post').default>>>>
    }
    '/api/store/categories': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/categories.post').default>>>>
    }
    '/api/store': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/index.post').default>>>>
    }
    '/api/store/mine': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/store/mine.get').default>>>>
    }
    '/api/stores/:slug/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/[slug]/categories.get').default>>>>
    }
    '/api/stores/:slug': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/[slug]/index.get').default>>>>
    }
    '/api/stores/:slug/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/[slug]/products.get').default>>>>
    }
    '/api/stores': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/stores/index.get').default>>>>
    }
    '/api/subscription/callback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/subscription/callback.post').default>>>>
    }
    '/api/track': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/track.get').default>>>>
    }
    '/api/vouchers/validate': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/vouchers/validate.post').default>>>>
    }
    '/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/google.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}