// Generated by nitro
import type { Serialize, Simplify } from "nitropack/types";
declare module "nitropack/types" {
  type Awaited<T> = T extends PromiseLike<infer U> ? Awaited<U> : T
  interface InternalApi {
    '/api/admin/admins': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins.post').default>>>>
    }
    '/api/admin/admins/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/admins/[id].delete').default>>>>
    }
    '/api/admin/categories/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/[id].delete').default>>>>
    }
    '/api/admin/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/categories/index.post').default>>>>
    }
    '/api/admin/chat/:sessionId/reply': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/chat/[sessionId]/reply.post').default>>>>
    }
    '/api/admin/chat': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/chat/index.get').default>>>>
    }
    '/api/admin/flash-sale/config': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/config.post').default>>>>
    }
    '/api/admin/flash-sale/sessions/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/[id].delete').default>>>>
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/[id].patch').default>>>>
    }
    '/api/admin/flash-sale/sessions': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/flash-sale/sessions/index.get').default>>>>
    }
    '/api/admin/login': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/login.post').default>>>>
    }
    '/api/admin/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/logout.post').default>>>>
    }
    '/api/admin/orders/:id/cancel': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/cancel.patch').default>>>>
    }
    '/api/admin/orders/:id/notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/notify.post').default>>>>
    }
    '/api/admin/orders/:id/shipment': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/shipment.post').default>>>>
    }
    '/api/admin/orders/:id/status': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/status.patch').default>>>>
    }
    '/api/admin/orders/:id/upload-proof': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/[id]/upload-proof.post').default>>>>
    }
    '/api/admin/orders/bulk-notify': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/bulk-notify.post').default>>>>
    }
    '/api/admin/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/index.get').default>>>>
    }
    '/api/admin/orders/offline': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/orders/offline.post').default>>>>
    }
    '/api/admin/products/:id': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/[id].delete').default>>>>
    }
    '/api/admin/products/:id/stock': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/[id]/stock.patch').default>>>>
    }
    '/api/admin/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/index.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/products/index.post').default>>>>
    }
    '/api/admin/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/settings.put').default>>>>
    }
    '/api/admin/wa-template': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/wa-template.get').default>>>>
      'put': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/admin/wa-template.put').default>>>>
    }
    '/api/auth/logout': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/logout.post').default>>>>
    }
    '/api/auth/me': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/me.get').default>>>>
    }
    '/api/auth/send-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/send-otp.post').default>>>>
    }
    '/api/auth/verify-otp': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/auth/verify-otp.post').default>>>>
    }
    '/api/buyer/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buyer/orders.get').default>>>>
    }
    '/api/buyer/password': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buyer/password.patch').default>>>>
    }
    '/api/buyer/profile': {
      'patch': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/buyer/profile.patch').default>>>>
    }
    '/api/categories': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/categories/index.get').default>>>>
    }
    '/api/chat/:sessionId/messages': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/[sessionId]/messages.get').default>>>>
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/[sessionId]/messages.post').default>>>>
    }
    '/api/chat/start': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/chat/start.post').default>>>>
    }
    '/api/checkout/regular': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/checkout/regular.post').default>>>>
    }
    '/api/flash-sale/config': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/flash-sale/config.get').default>>>>
    }
    '/api/orders/:id/track': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/[id]/track.get').default>>>>
    }
    '/api/orders': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/orders/index.get').default>>>>
    }
    '/api/payment/callback': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/callback.post').default>>>>
    }
    '/api/payment/create-transaction': {
      'post': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/create-transaction.post').default>>>>
    }
    '/api/payment/settings': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/payment/settings.get').default>>>>
    }
    '/api/products/:id': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/[id].get').default>>>>
    }
    '/api/products': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/index.get').default>>>>
    }
    '/api/products/status': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/status.get').default>>>>
    }
    '/api/products/stock': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/products/stock.get').default>>>>
    }
    '/api/s3-image/**:path': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/s3-image/[...path].get').default>>>>
    }
    '/api/shipping/cities': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shipping/cities.get').default>>>>
    }
    '/api/shipping/cost': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/shipping/cost.get').default>>>>
    }
    '/api/track': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/api/track.get').default>>>>
    }
    '/auth/google': {
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/routes/auth/google.get').default>>>>
    }
    '/__nuxt_error': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/nitro-server/dist/runtime/handlers/renderer').default>>>>
    }
    '/api/_nuxt_icon/:collection': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/icon/dist/runtime/server/api').default>>>>
    }
    '/_scripts/p/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/@nuxt/scripts/dist/runtime/server/proxy-handler').default>>>>
    }
    '/api/_auth/session': {
      'delete': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.delete').default>>>>
      'get': Simplify<Serialize<Awaited<ReturnType<typeof import('../../node_modules/nuxt-auth-utils/dist/runtime/server/api/session.get').default>>>>
    }
    '/__nuxt_island/**': {
      'default': Simplify<Serialize<Awaited<ReturnType<typeof import('../../server/#internal/nuxt/island-renderer').default>>>>
    }
  }
}
export {}