// Generated by @nuxt/scripts
declare module '#app' {
  interface NuxtApp {
    $scripts: Record<string, import('#nuxt-scripts/types').UseScriptContext<any> | undefined>
    _scripts: Record<string, import('#nuxt-scripts/types').NuxtDevToolsScriptInstance>
  }
  interface RuntimeNuxtHooks {
    'scripts:updated': (ctx: { scripts: Record<string, import('#nuxt-scripts/types').NuxtDevToolsScriptInstance> }) => void | Promise<void>
    // Index signature (not a literal-key Record) so listeners can both `delete globals[key]`
    // and mutate `globals[key].src` without TS2790 / possibly-undefined errors.
    'scripts:globals': (globals: Record<string, Record<string, any>>) => void | Promise<void>
  }
}

export {}